import { useEffect, useRef, memo } from 'react'
import { motion } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import './PrivacyPolicy.css'

gsap.registerPlugin(ScrollTrigger)

const pageVariants = {
    initial: { opacity: 0 },
    animate: { opacity: 1, transition: { duration: 0.6 } },
    exit: { opacity: 0, transition: { duration: 0.3 } }
}

const PrivacyPolicy = memo(() => {
    const pageRef = useRef(null)

    useEffect(() => {
        const ctx = gsap.context(() => {
            gsap.fromTo('.pp-section', 
                { opacity: 0, y: 30 },
                { opacity: 1, y: 0, duration: 0.8, stagger: 0.15, scrollTrigger: { trigger: '.pp-content', start: 'top 80%' } }
            )
            
            gsap.fromTo('.pp-divider',
                { scaleX: 0 },
                { scaleX: 1, duration: 1, transformOrigin: 'left center', stagger: 0.2, scrollTrigger: { trigger: '.pp-content', start: 'top 80%' } }
            )
        }, pageRef)
        return () => ctx.revert()
    }, [])

    return (
        <motion.main className="pp-page" ref={pageRef} variants={pageVariants} initial="initial" animate="animate" exit="exit">
            <section className="pp-hero">
                <div className="pp-hero-bg" />
                <div className="pp-hero-gradient" />
                <div className="container" style={{ position: 'relative', zIndex: 2 }}>
                    <div className="section-label" style={{ justifyContent: 'flex-start' }}>Legal Information</div>
                    <h1 className="heading-xl">
                        Privacy <span className="gradient-text">Policy</span>
                    </h1>
                    <div className="pp-last-updated">Last Updated: March 2026</div>
                </div>
            </section>

            <section className="pp-content">
                <div className="container">
                    <div className="pp-document">
                        
                        <div className="pp-intro pp-section">
                            <p className="text-body large-text">
                                At 3rdAI, we are committed to protecting your privacy and ensuring the security of your data. This policy outlines how we handle your information in our advanced intelligence systems, computer vision platforms, and related services.
                            </p>
                        </div>

                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">1. Information Collection</h2>
                            <p className="text-body">
                                Our autonomous AI intelligence platform may collect various types of data depending on your interaction with our services. The categories of data we collect include:
                            </p>
                            <ul className="pp-list">
                                <li><strong>Account Information:</strong> Name, email address, corporate credentials, and contact details used for provisioning Control Center access.</li>
                                <li><strong>Usage Telemetry:</strong> System interactions, audit logs, configuration settings, and performance metrics from the deployment of 3rdAI edge devices.</li>
                                <li><strong>Visual Data:</strong> Video streams and image frames processed by our edge and cloud neural networks, strictly in accordance with client agreements and applicable local surveillance laws.</li>
                            </ul>
                        </div>

                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">2. Data Processing & AI Analysis</h2>
                            <p className="text-body">
                                Insights generated by our Vision AI Core are strictly utilized for security, behavioral analysis, and threat prediction as authorized by our clients. Our systems are designed with privacy-by-design principles:
                            </p>
                            <ul className="pp-list">
                                <li>Real-time processing primarily occurs at the edge to minimize data transmission.</li>
                                <li>Personal identifiable information (PII) is anonymized or hashed where technically feasible.</li>
                                <li>Long-term storage of raw video is dictated by the client's retention policies, not by 3rdAI's default models.</li>
                            </ul>
                        </div>

                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">3. Data Security & Encryption Architecture</h2>
                            <p className="text-body">
                                We employ AES-256-GCM encryption for all data in transit and at rest. Our infrastructure operates on a zero-trust model utilizing hardware security module (HSM) clusters to ensure absolute data integrity. Access to sensitive data is protected by multi-factor authentication and role-based access controls (RBAC).
                            </p>
                        </div>

                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">4. Sharing and Disclosure</h2>
                            <p className="text-body">
                                3rdAI does not sell your personal data. Data may only be shared under the following circumstances:
                            </p>
                            <ul className="pp-list">
                                <li><strong>With Service Providers:</strong> Trusted third-party vendors who assist in operating our platform, bound by strict confidentiality agreements.</li>
                                <li><strong>Legal Requirements:</strong> With judicial bodies or law enforcement strictly when mandated by legally binding requests or regulatory compliances.</li>
                                <li><strong>Client Authorization:</strong> As configured by the authorized administrators of the 3rdAI system deployment.</li>
                            </ul>
                        </div>
                        
                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">5. Your Data Rights</h2>
                            <p className="text-body">
                                Depending on your jurisdiction (e.g., GDPR, CCPA), you may have rights to access, correct, delete, or restrict the processing of your personal information. To exercise these rights involving data processed by a 3rdAI client, please contact the respective organization acting as the data controller. For data where 3rdAI is the controller, contact us directly.
                            </p>
                        </div>

                        <div className="pp-divider" />

                        <div className="pp-section">
                            <h2 className="pp-heading">6. Contact Information</h2>
                            <p className="text-body">
                                For any compliance inquiries, security reports, or data requests regarding your interactions with our neural networks, please contact our data protection team via our secure channels.
                            </p>
                            <div className="pp-contact-info">
                                <p><strong>Email:</strong> contact@diintech.com</p>
                                <p><strong>Address:</strong> C-116, Sector-2, Noida, Uttar Pradesh – 201301, India</p>
                                <p><strong>Phone:</strong> +91 81475 40362</p>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
        </motion.main>
    )
})

PrivacyPolicy.displayName = 'PrivacyPolicy'

export default PrivacyPolicy
